### ISSUE TITLE
projection for openlayers

### ISSUE THREAD

**Issue by heinzwilli** [bouviervj/topojson-j#3]
First of all thanks for this great project. I don't know if this is the right place to ask questions but I didn't find any other contact information.
I'm trying to use topojson-j to generate topojson for openlayers (http://openlayers.org/) but somehow the projection is messed up. You can find the shapefile I'm using at http://www.arcgis.com/home/item.html?id=ae25571c60d94ce5b7fcbf74e27c00e0 in this archive there is a vg2500_krs.shp. My attempt was to convert the shapefile to the right projection using ogr2ogr but this didn't work correctly. The new topojson-j version is able to convert the projection. Can you tell me how to configure topojson-j to get a openlayers compatible projection (e.g. EPSG:3857)? Your test shapefile MA.shp seems to work. It can be tested easily on http://openlayers.org/en/v3.4.0/examples/drag-and-drop.html. 

Thanks in advance 
Peter 

![image](https://cloud.githubusercontent.com/assets/11979908/7183474/f28a9cb4-e457-11e4-951e-bfc4d91a758e.png)

**Comment by heinzwilli** [comment]
Solved it by using projection for germany (epsg:31467)

**Comment by bouviervj** [comment]
Hi,

Sorry for late reply, I see that you found a solution to your issue. In fact I'm using a library to proceed to projections correction. I have not releases my version, but I can give you the link to the site I found the implementation : http://www.jhlabs.com/java/maps/proj/ 
The base point to me, is that we start with a shape file, that is recorded with a certain projection system. I have to take those coordinate and I transform them in lon, lat coordinates. For example, the MA.shp is recorded with nad83:2001 system. The library I'm using is configured with 3-4 files containing parameters to proceed this conversion. I checked quickly your conversion mode 'EPSG:3857' and didn't find it in espg file.
Glads you found an equivalent, but for your map system, isn't it easier to have lon/lat coordinate projection system ? 
An other point you raised is that it would be cool to encode at least Geojson or TopoJson with a specific coordinate system.

Cheers,
Julien

**Comment by bouviervj** [comment]
An other point, a shp file comes with linked files, and one that describes it's coordinates system, It should be great to decode it and have a direct conversion of system coordinate.

**Comment by heinzwilli** [comment]
Hi,
thanks for your reply. I will give lon/lat coordinates a try. Reading the coordinate system out of the shapefile would make your library even easier to use but in my opinion it isn't important because it doesn't provide any additional features.
